name: ForDev
description: Enquete para programadores.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  http:
  material: 

dev_dependencies:
  flutter_launcher_icons:
  flutter_test:
    sdk: flutter
  test: 
  mockito: 3.0.2
  faker: 1.3.0

flutter:
  uses-material-design: true
  assets:
    - lib/ui/assets/

flutter_icons:
  ios: true
  android: true
  image_path_android: lib/ui/assets/icon/android.png
  image_path_ios: lib/ui/assets/icon/ios.png
  adaptive_icon_background: lib/ui/assets/icon/background.png
  adaptive_icon_foreground: lib/ui/assets/icon/foreground.png
#
#run: fvm flutter pub run flutter_launcher_icons:main